./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr1.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr1.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr2.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr2.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr3.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr3.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr4.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr4.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr5.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr5.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr6.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr6.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr7.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr7.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr8.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr8.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr9.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr9.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr10.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr10.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr11.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr11.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr12.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr12.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr13.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr13.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr14.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr14.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr15.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr15.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr16.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr16.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr17.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr17.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr18.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr18.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr19.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr19.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr20.txt /r02/radnet/genetics/FinalSampleFiles/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr20txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr21.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr21.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr22.txt /r02/radnet/genetics/FinalGWASResults/statacutephenotypes.sample -frequentist 1 -method expected -pheno STAT_residuals -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_statacute2_chr22.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr1.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr1.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr2.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr2.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr3.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr3.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr4.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr4.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr5.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr5.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr6.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr6.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr7.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr7.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr8.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr8.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr9.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr9.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr10.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr10.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr11.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr11.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr12.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr12.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr13.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr13.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr14.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr14.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr15.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr15.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr16.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr16.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr17.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr17.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr18.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr18.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr19.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr19.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr20.txt /r02/radnet/genetics/FinalSampleFiles/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr20txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr21.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr21.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr22.txt /r02/radnet/genetics/FinalGWASResults/xerostomiaphenotypes.sample -frequentist 1 -method expected -pheno xero_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_xerostomia_chr22.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr1.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr1.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr2.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr2.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr3.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr3.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr4.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr4.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr5.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr5.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr6.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr6.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr7.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr7.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr8.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr8.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr9.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr9.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr10.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr10.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr11.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr11.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr12.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr12.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr13.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr13.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr14.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr14.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr15.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr15.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr16.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr16.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr17.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr17.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr18.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr18.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr19.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr19.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr20.txt /r02/radnet/genetics/FinalSampleFiles/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr20txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr21.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr21.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr22.txt /r02/radnet/genetics/FinalGWASResults/dysphagiaphenotypes.sample -frequentist 1 -method expected -pheno dys_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_dysphagia_chr22.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr1.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr1.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr2.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr2.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr3.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr3.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr4.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr4.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr5.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr5.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr6.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr6.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr7.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr7.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr8.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr8.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr9.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr9.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr10.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr10.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr11.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr11.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr12.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr12.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr13.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr13.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr14.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr14.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr15.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr15.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr16.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr16.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr17.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr17.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr18.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr18.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr19.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr19.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr20.txt /r02/radnet/genetics/FinalSampleFiles/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr20txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr21.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr21.txt
./snptest_v2.4.1 -data /r02/radnet/genetics/rapper_nimrad_chr22.txt /r02/radnet/genetics/FinalGWASResults/mucositisphenotypes.sample -frequentist 1 -method expected -pheno muco_residuals -cov_all -o /r02/radnet/genetics/FinalGWASResults/RAPPER_NIMRAD_mucositis_chr22.txt
